/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BillItem {
  'itemId' : ItemId,
  'itemName' : string,
  'quantity' : bigint,
  'subtotal' : number,
}
export type BillNumber = bigint;
export interface BillRecord {
  'studentName' : string,
  'date' : string,
  'grandTotal' : number,
  'number' : BillNumber,
  'paymentMode' : PaymentMode,
  'items' : Array<BillItem>,
  'studentClass' : string,
}
export interface InventoryItem {
  'id' : ItemId,
  'name' : string,
  'pricePerItem' : number,
  'quantity' : bigint,
  'category' : ItemCategory,
}
export type ItemCategory = string;
export type ItemId = bigint;
export type PaymentMode = { 'upi' : null } |
  { 'cash' : null };
export interface _SERVICE {
  'addItem' : ActorMethod<[string, ItemCategory, bigint, number], ItemId>,
  'createBill' : ActorMethod<
    [string, string, Array<BillItem>, PaymentMode, string],
    BillNumber
  >,
  'getBillsByDate' : ActorMethod<[string], Array<BillRecord>>,
  'getItems' : ActorMethod<[], Array<InventoryItem>>,
  'getNextBillNumber' : ActorMethod<[], bigint>,
  'getTotals' : ActorMethod<
    [],
    {
      'totalStockAvailable' : bigint,
      'totalIncomeToday' : number,
      'totalStockSoldToday' : bigint,
      'totalItems' : bigint,
    }
  >,
  'updateItem' : ActorMethod<
    [ItemId, string, ItemCategory, bigint, number],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];