/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ItemCategory = IDL.Text;
export const ItemId = IDL.Nat;
export const BillItem = IDL.Record({
  'itemId' : ItemId,
  'itemName' : IDL.Text,
  'quantity' : IDL.Nat,
  'subtotal' : IDL.Float64,
});
export const PaymentMode = IDL.Variant({ 'upi' : IDL.Null, 'cash' : IDL.Null });
export const BillId = IDL.Nat;
export const BillRecord = IDL.Record({
  'id' : BillId,
  'studentName' : IDL.Text,
  'date' : IDL.Text,
  'grandTotal' : IDL.Float64,
  'paymentMode' : PaymentMode,
  'items' : IDL.Vec(BillItem),
});
export const InventoryItem = IDL.Record({
  'id' : ItemId,
  'name' : IDL.Text,
  'pricePerItem' : IDL.Float64,
  'quantity' : IDL.Nat,
  'category' : ItemCategory,
});

export const idlService = IDL.Service({
  'addItem' : IDL.Func(
      [IDL.Text, ItemCategory, IDL.Nat, IDL.Float64],
      [ItemId],
      [],
    ),
  'createBill' : IDL.Func(
      [IDL.Text, IDL.Vec(BillItem), PaymentMode],
      [BillId],
      [],
    ),
  'getBillsByDate' : IDL.Func([IDL.Text], [IDL.Vec(BillRecord)], ['query']),
  'getItems' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
  'getTotals' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalStockAvailable' : IDL.Nat,
          'totalIncomeToday' : IDL.Float64,
          'totalStockSoldToday' : IDL.Nat,
          'totalItems' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'updateItem' : IDL.Func(
      [ItemId, IDL.Text, ItemCategory, IDL.Nat, IDL.Float64],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ItemCategory = IDL.Text;
  const ItemId = IDL.Nat;
  const BillItem = IDL.Record({
    'itemId' : ItemId,
    'itemName' : IDL.Text,
    'quantity' : IDL.Nat,
    'subtotal' : IDL.Float64,
  });
  const PaymentMode = IDL.Variant({ 'upi' : IDL.Null, 'cash' : IDL.Null });
  const BillId = IDL.Nat;
  const BillRecord = IDL.Record({
    'id' : BillId,
    'studentName' : IDL.Text,
    'date' : IDL.Text,
    'grandTotal' : IDL.Float64,
    'paymentMode' : PaymentMode,
    'items' : IDL.Vec(BillItem),
  });
  const InventoryItem = IDL.Record({
    'id' : ItemId,
    'name' : IDL.Text,
    'pricePerItem' : IDL.Float64,
    'quantity' : IDL.Nat,
    'category' : ItemCategory,
  });
  
  return IDL.Service({
    'addItem' : IDL.Func(
        [IDL.Text, ItemCategory, IDL.Nat, IDL.Float64],
        [ItemId],
        [],
      ),
    'createBill' : IDL.Func(
        [IDL.Text, IDL.Vec(BillItem), PaymentMode],
        [BillId],
        [],
      ),
    'getBillsByDate' : IDL.Func([IDL.Text], [IDL.Vec(BillRecord)], ['query']),
    'getItems' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
    'getTotals' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalStockAvailable' : IDL.Nat,
            'totalIncomeToday' : IDL.Float64,
            'totalStockSoldToday' : IDL.Nat,
            'totalItems' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'updateItem' : IDL.Func(
        [ItemId, IDL.Text, ItemCategory, IDL.Nat, IDL.Float64],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };